name: Release

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Build Binaries
        run: |
          mkdir -p dist
          deno compile --output dist/curlgen-linux-amd64 --allow-env --allow-run --allow-net --allow-read --allow-write --target x86_64-unknown-linux-gnu main.ts
          deno compile --output dist/curlgen-macos-amd64 --allow-env --allow-run --allow-net --allow-read --allow-write --target x86_64-apple-darwin main.ts
          deno compile --output dist/curlgen-macos-arm64 --allow-env --allow-run --allow-net --allow-read --allow-write --target aarch64-apple-darwin main.ts
          deno compile --output dist/curlgen-windows-amd64.exe --allow-env --allow-run --allow-net --allow-read --allow-write --target x86_64-pc-windows-msvc main.ts

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/curlgen-linux-amd64
            dist/curlgen-macos-amd64
            dist/curlgen-macos-arm64
            dist/curlgen-windows-amd64.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
